version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      ui:
        patterns:
          ["next", "react", "react-dom", "eslint-config-next", "@types/react*"]
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
