[package]
name = "gradavia-edge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gradavia-read-model = { path = "../read-model" }
serde_json = "1"
sha2 = "0.10"
worker = "=0.8.7"

[lints]
workspace = true
